services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blockchain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d blockchain" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DB_NAME: blockchain
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db-setup:
    build: .
    command: python3 dbSetup.py
    environment:
      DB_NAME: blockchain
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  ingest:
    build: .
    command: python3 dataFetch.py
    volumes:
      - .:/app
    environment:
      DB_NAME: blockchain
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db-setup:
        condition: service_completed_successfully

volumes:
  postgres_data:
